// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const http: typeof import('axios')['default']
  const IconBiExclamationTriangleFill: typeof import('~icons/bi/exclamation-triangle-fill.jsx')['default']
  const IconCarbonLanguage: typeof import('~icons/carbon/language.jsx')['default']
  const IconCarbonLight: typeof import('~icons/carbon/light.jsx')['default']
  const IconCarbonMoon: typeof import('~icons/carbon/moon.jsx')['default']
  const IconMdiBellOutline: typeof import('~icons/mdi/bell-outline.jsx')['default']
  const IconMdiBitcoin: typeof import('~icons/mdi/bitcoin.jsx')['default']
  const IconMdiHome: typeof import('~icons/mdi/home.jsx')['default']
  const IconMdiInformation: typeof import('~icons/mdi/information.jsx')['default']
  const IconMdiLogout: typeof import('~icons/mdi/logout.jsx')['default']
  const IconMdiMenu: typeof import('~icons/mdi/menu.jsx')['default']
  const IconMdiSettings: typeof import('~icons/mdi/settings.jsx')['default']
  const initReactI18next: typeof import('react-i18next')['initReactI18next']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
export {}
