// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const http: typeof import('axios')['default']
  const IconCarbonChevronLeft: typeof import('~icons/carbon/chevron-left.jsx')['default']
  const IconCarbonChevronRight: typeof import('~icons/carbon/chevron-right.jsx')['default']
  const IconCarbonLanguage: typeof import('~icons/carbon/language.jsx')['default']
  const IconCarbonLight: typeof import('~icons/carbon/light.jsx')['default']
  const IconCarbonMoon: typeof import('~icons/carbon/moon.jsx')['default']
  const IconMdiBellOutline: typeof import('~icons/mdi/bell-outline.jsx')['default']
  const IconMdiLogout: typeof import('~icons/mdi/logout.jsx')['default']
  const IconMdiSettings: typeof import('~icons/mdi/settings.jsx')['default']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
export {}
